name: edu_cope
description: Project help to connect tutor and st

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  retrofit: ^2.0.0
  dio: ^4.0.0
  notification_permissions: ^0.4.0
  firebase_analytics: ^8.0.2
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.0
  firebase_messaging_platform_interface: ^3.0.0
  shared_preferences_platform_interface: ^2.0.0
  shared_preferences_windows: ^2.0.0
  http_parser: ^4.0.0
  stomp_dart_client: ^0.4.2
  scroll_to_index: ^1.0.6
  dart_amqp: ^0.2.0
  uuid: 3.0.4
  enum_to_string: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0+1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.2
  build_runner: ^2.0.3
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: ^0.9.2
  percent_indicator: ^2.1.7+2
  image_picker: ^0.7.4

flutter_native_splash:
  color: "#ffffff"
  image: asset/image/logo-edu-3-laucher.png

flutter_icons:
  android: true
  image_path: asset/image/logo-edu-3-laucher.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - asset/image/logo-1.jpeg
    - asset/image/teacher.png
    - asset/image/parent.png
    - asset/image/add.png
    - asset/image/blank-account.jpg
    - asset/image/class.png
    - asset/image/homepage.png
    - asset/image/map.png
    - asset/image/next.png
    - asset/image/payment.png
    - asset/image/message.png
    - asset/image/notification.png
    - asset/image/comment.png
    - asset/image/personal.png
    - asset/image/setting.png
    - asset/image/sign-out.png
    - asset/image/rating-star.png
    - asset/image/edit.png
    - asset/image/file.png
    - asset/image/adjust.png
    - asset/image/cancel.png
    - asset/image/class_information.png
    - asset/image/class_status.png
    - asset/image/homepage_green.png
    - asset/image/personal_green.png
    - asset/image/personal_blue.png
    - asset/image/reject.png
    - asset/image/accept.png
    - asset/image/contract.png
    - asset/image/attendance.png
    - asset/image/chat-user-profile.png
    - asset/image/forum.png
    - asset/image/logo-edu-1.png
    - asset/image/logo-edu-2.png
    - asset/image/logo-edu-3.png
    - asset/image/profile-image-1.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
